# Project: 神奇寶貝4結構傳入函式多檔案
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o pokemon.o
LINKOBJ  = main.o pokemon.o
LIBS     = -L"C:/Users/malia/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/malia/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/malia/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/malia/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/malia/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/malia/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/malia/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/malia/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/malia/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 神奇寶貝4結構傳入函式多檔案.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CPP) -c main.c -o main.o $(CXXFLAGS)

pokemon.o: pokemon.c
	$(CPP) -c pokemon.c -o pokemon.o $(CXXFLAGS)
